[package]
name = "torrent_router"
version = "0.1.0"
authors = ["jdon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0.15"
lava_torrent = "0.5.0"
url = "2.1.1"